openapi: 3.0.3
info:
  title: 'Vehicle APi Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://103.123.8.225:8091'
paths:
  /api/v1/register:
    post:
      summary: 'Benutzer Registration'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: X-api-version
          description: ''
          example: rerum
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'User register successful. Please check otp'
                  code: 200
                  data:
                    user:
                      id: 6
                      full_name: pmnasrcjlajnaciztjrwqchmnjmwglepjjauiansyopfvrvfqpidhadtkilkugjzjcwrahudqbmxtfzthu
                      email: trantow.elsa@example.org
                      phone: quasi
                      email_verified_at: null
                      last_login: null
                      created_at: '2022-01-24T12:15:58.000000Z'
                      updated_at: '2022-01-24T12:15:58.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User register successful. Please check otp'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    example:
                      user:
                        id: 6
                        full_name: pmnasrcjlajnaciztjrwqchmnjmwglepjjauiansyopfvrvfqpidhadtkilkugjzjcwrahudqbmxtfzthu
                        email: trantow.elsa@example.org
                        phone: quasi
                        email_verified_at: null
                        last_login: null
                        created_at: '2022-01-24T12:15:58.000000Z'
                        updated_at: '2022-01-24T12:15:58.000000Z'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: pmnasrcjlajnaciztjrwqchmnjmwglepjjauiansyopfvrvfqpidhadtkilkugjzjcwrahudqbmxtfzthu
                email:
                  type: string
                  description: validation.email.
                  example: trantow.elsa@example.org
                phone:
                  type: string
                  description: ''
                  example: quasi
                password:
                  type: string
                  description: ''
                  example: voluptatem
              required:
                - full_name
                - phone
                - password
      security: []
  /api/v1/login:
    post:
      summary: Anmelde-API
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Benutzeranmeldung erfolgreich..'
                  code: 200
                  data:
                    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNGU2MjkzYjk3NjgxMzgyMjM4OTIxYjQzNTlkYzRkN2YxNWJjODc5MDdjMTFjY2JkM2I0YzM3ODlmNjQyMDBkOTM0YjhmODNiYzgyNzkwNmEiLCJpYXQiOjE2NDI2NzM4NTguNjU1MzE5LCJuYmYiOjE2NDI2NzM4NTguNjU1MzI0LCJleHAiOjE2NDM5Njk4NTguNjQ4NTAxLCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.O5NNZdmSoqbwK2-wWg6rrAFtWaUUe9JnybMtuoHJBReohF0ois9N9-x7CzOPuX4aKmE61LlPsM6DbIm-yidvqfGOT73mVYoREwu2mISiqTUqsbu8mnq6Nsq6Z_rj21VbOp2-DqkWh86PPI5kpf-t_-pt1QlLAwveTVpefbnmUmfc49m-_aOnXDM2H6QKhXt9zVqlkj2tgFjKgfISqLGJ_iWxUvaHzCSNDMvp7K1Cu620rT5VXCBzDi5NIXuHaCQ7KOzoMT5m5Upb-kG0TjERWogVPUjP8sY4H5AY3PYGkmZfjaRFn6QDth2Fk1fl1-DQffDFsUzuzLvfnbplLr6LfHJnAJFUvsbQpYd_F8-yOcP0JmMn-_Q8P2gtLxD4kL_ofy4cPxi66h6Apc3IeN-7bqd059lmo2uBn_mAZYUdpT8Zo83PeM2ShioUlpUXCCtqnmN4N6R3w2whZfp0Qm-9-9Hy9uGbVb5eNS24rN1XZ27JveT7LRSMU213wqdiKIOOhBXTr3frz2MzXDEk7Fisx9BkzvrHBHbV0ES2mm2zZgha3GqTXw1qH7ENr_W4BClsJL0ArT_a-oifyBFIi_QNKzeNPz439hnSy6YLRKD-3O35ZizIh4u2i7kYpwm25gnxp01zj9PG4Mg0BVrP8OlSuZJyfPslXWmmtg6_NEEh1BY
                    user:
                      id: 4
                      full_name: 'Ariful Islam'
                      email: null
                      phone: '01750840217'
                      email_verified_at: null
                      last_login: null
                      created_at: '2022-01-20T09:38:29.000000Z'
                      updated_at: '2022-01-20T09:38:29.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Benutzeranmeldung erfolgreich..'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    example:
                      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNGU2MjkzYjk3NjgxMzgyMjM4OTIxYjQzNTlkYzRkN2YxNWJjODc5MDdjMTFjY2JkM2I0YzM3ODlmNjQyMDBkOTM0YjhmODNiYzgyNzkwNmEiLCJpYXQiOjE2NDI2NzM4NTguNjU1MzE5LCJuYmYiOjE2NDI2NzM4NTguNjU1MzI0LCJleHAiOjE2NDM5Njk4NTguNjQ4NTAxLCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.O5NNZdmSoqbwK2-wWg6rrAFtWaUUe9JnybMtuoHJBReohF0ois9N9-x7CzOPuX4aKmE61LlPsM6DbIm-yidvqfGOT73mVYoREwu2mISiqTUqsbu8mnq6Nsq6Z_rj21VbOp2-DqkWh86PPI5kpf-t_-pt1QlLAwveTVpefbnmUmfc49m-_aOnXDM2H6QKhXt9zVqlkj2tgFjKgfISqLGJ_iWxUvaHzCSNDMvp7K1Cu620rT5VXCBzDi5NIXuHaCQ7KOzoMT5m5Upb-kG0TjERWogVPUjP8sY4H5AY3PYGkmZfjaRFn6QDth2Fk1fl1-DQffDFsUzuzLvfnbplLr6LfHJnAJFUvsbQpYd_F8-yOcP0JmMn-_Q8P2gtLxD4kL_ofy4cPxi66h6Apc3IeN-7bqd059lmo2uBn_mAZYUdpT8Zo83PeM2ShioUlpUXCCtqnmN4N6R3w2whZfp0Qm-9-9Hy9uGbVb5eNS24rN1XZ27JveT7LRSMU213wqdiKIOOhBXTr3frz2MzXDEk7Fisx9BkzvrHBHbV0ES2mm2zZgha3GqTXw1qH7ENr_W4BClsJL0ArT_a-oifyBFIi_QNKzeNPz439hnSy6YLRKD-3O35ZizIh4u2i7kYpwm25gnxp01zj9PG4Mg0BVrP8OlSuZJyfPslXWmmtg6_NEEh1BY
                      user:
                        id: 4
                        full_name: 'Ariful Islam'
                        email: null
                        phone: '01750840217'
                        email_verified_at: null
                        last_login: null
                        created_at: '2022-01-20T09:38:29.000000Z'
                        updated_at: '2022-01-20T09:38:29.000000Z'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Phone number.'
                  example: 017XXXXXXXX
                password:
                  type: string
                  description: 'Password of user.'
                  example: test@example.com
              required:
                - phone
                - password
      security: []
  /api/v1/vehicle/add:
    post:
      summary: 'Neues Fahrzeug hinzufügen'
      description: 'Dadurch wird der Datenbank ein neues Fahrzeug hinzugefügt'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Fahrzeugadresse erfolgreich hinzugefügt'
                  code: 201
                  data: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Fahrzeugadresse erfolgreich hinzugefügt'
                  code:
                    type: integer
                    example: 201
                  data:
                    type: array
                    example: []
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                herstellerin:
                  type: string
                  description: 'Name of herstellerin.'
                  example: Toyota
                modell:
                  type: string
                  description: 'modell number of vehicle.'
                  example: 74CUG
                fin:
                  type: string
                  description: 'Identification number of vehicle.'
                  example: '754454'
                erste_registrierung:
                  type: date
                  description: 'Date format should be YYYY-mm-dd'
                  example: '2020-12-12'
                kilometerstand:
                  type: integer
                  description: 'How much vehicles can drive.'
                  example: 40
              required:
                - herstellerin
                - modell
                - fin
  /api/v1/vehicle/all:
    post:
      summary: 'Holen Sie sich alle Fahrzeuge'
      description: 'Dadurch werden alle Fahrzeugdaten aus der Datenbank ausgewählt und abgerufen'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{{\n\"success\": true,\n\"message\": \"Abgeholte Fahrzeuge\",\n\"code\": 200,\n\"data\": [\n{\n\"id\": 2,\n\"herstellerin\": \"27575\",\n\"modell\": \"28588\",\n\"fin\": \"45678d\",\n\"erste_registrierung\": \"0222-01-20\",\n\"kilometerstand\": 654564,\n\"erstellt_am\": \"2022-01-20T09:44:16.000000Z\",\n\"aktualisiert_am\": \"2022-01-20T10:03:33.000000Z\"\n},\n{\n\"id\": 3,\n\"herstellerin\": \"Toyota\",\n\"modell\": \"285TC\",\n\"fin\": \"96876\",\n\"erste_registrierung\": \"1997-01-20\",\n\"kilometerstand\": 40,\n\"erstellt_am\": \"2022-01-20T09:44:32.000000Z\",\n\"aktualisiert_am\": \"2022-01-20T09:44:32.000000Z\"\n},\n{\n\"id\": 4,\n\"herstellerin\": \"BMW\",\n\"modell\": \"BM54\",\n\"fin\": \"78654F\",\n\"erste_registrierung\": \"1997-01-20\",\n\"kilometerstand\": 140,\n\"erstellt_am\": \"2022-01-20T09:44:55.000000Z\",\n\"aktualisiert_am\": \"2022-01-20T09:44:55.000000Z\"\n},\n{\n\"id\": 5,\n\"herstellerin\": \"BMW\",\n\"modell\": \"BM754\",\n\"fin\": \"23456B\",\n\"erste_registrierung\": \"2022-01-20\",\n\"kilometerstand\": 180,\n\"erstellt_am\": \"2022-01-20T09:45:18.000000Z\",\n\"aktualisiert_am\": \"2022-01-20T09:45:18.000000Z\"\n},\n{\n\"id\": 6,\n\"herstellerin\": \"Audi\",\n\"modell\": \"AUD78541\",\n\"fin\": \"854694\",\n\"erste_registrierung\": \"2022-01-20\",\n\"kilometerstand\": 180,\n\"erstellt_am\": \"2022-01-20T09:45:32.000000Z\",\n\"aktualisiert_am\": \"2022-01-20T09:45:32.000000Z\"\n}\n]\n}"
      tags:
        - Endpoints
  '/api/v1/vehicle/view/{id}':
    post:
      summary: 'Einzelfahrzeug anzeigen'
      description: 'Dies zeigt ein einzelnes Fahrzeug'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"success\": true,\n\"message\": \"Fahrzeug abgeholt\",\n\"code\": 200,\n\"data\": {\n\"id\": 2,\n\"herstellerin\": \"27575\",\n\"modell\": \"28588\",\n\"fin\": \"45678d\",\n\"erste_registrierung\": \"0222-01-20\","
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'It will be the id of vehicle in database.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/vehicle/edit/{id}':
    post:
      summary: 'Fahrzeug bearbeiten'
      description: 'Dadurch werden Fahrzeugdaten bearbeitet'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Fahrzeug erfolgreich aktualisiert'
                  code: 200
                  data: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Fahrzeug erfolgreich aktualisiert'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: array
                    example: []
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                herstellerin:
                  type: string
                  description: 'Name of herstellerin.'
                  example: Toyota
                modell:
                  type: string
                  description: 'modell number of vehicle.'
                  example: 74CUG
                fin:
                  type: string
                  description: 'Identification number of vehicle.'
                  example: '754454'
                erste_registrierung:
                  type: date
                  description: 'Date format should be YYYY-mm-dd.'
                  example: '2020-12-12'
                kilometerstand:
                  type: integer
                  description: 'How much vehicles can drive.'
                  example: 40
              required:
                - herstellerin
                - modell
                - fin
    parameters:
      -
        in: path
        name: id
        description: 'It will be the id of vehicle in database.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/vehicle/delete/{id}':
    post:
      summary: 'Fahrzeug löschen'
      description: 'Dadurch werden Daten aus der Datenbank gelöscht'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Fahrzeug erfolgreich gelöscht'
                  code: 200
                  data: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Fahrzeug erfolgreich gelöscht'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: array
                    example: []
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'It will be the id of vehicle in database.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: ''
  -
    name: Endpoints
    description: ''
