openapi: 3.0.3
info:
  title: 'Vehicle APi Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://103.123.8.225:8091'
paths:
  /api/v1/register:
    post:
      summary: 'User Registration'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: X-api-version
          description: ''
          example: nihil
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  code: 404
                  message: 'Invalid phone number'
                  data:
                    phone:
                      - 'provided phone number is invalid'
                properties:
                  success:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: 'Invalid phone number'
                  data:
                    type: object
                    example:
                      phone:
                        - 'provided phone number is invalid'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: yoficzjwq
                email:
                  type: string
                  description: validation.email.
                  example: otha79@example.org
                phone:
                  type: string
                  description: ''
                  example: sequi
                password:
                  type: string
                  description: ''
                  example: non
              required:
                - full_name
                - phone
                - password
      security: []
  /api/v1/login:
    post:
      summary: 'Login api'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'User login successfully.'
                  code: 200
                  data:
                    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNGU2MjkzYjk3NjgxMzgyMjM4OTIxYjQzNTlkYzRkN2YxNWJjODc5MDdjMTFjY2JkM2I0YzM3ODlmNjQyMDBkOTM0YjhmODNiYzgyNzkwNmEiLCJpYXQiOjE2NDI2NzM4NTguNjU1MzE5LCJuYmYiOjE2NDI2NzM4NTguNjU1MzI0LCJleHAiOjE2NDM5Njk4NTguNjQ4NTAxLCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.O5NNZdmSoqbwK2-wWg6rrAFtWaUUe9JnybMtuoHJBReohF0ois9N9-x7CzOPuX4aKmE61LlPsM6DbIm-yidvqfGOT73mVYoREwu2mISiqTUqsbu8mnq6Nsq6Z_rj21VbOp2-DqkWh86PPI5kpf-t_-pt1QlLAwveTVpefbnmUmfc49m-_aOnXDM2H6QKhXt9zVqlkj2tgFjKgfISqLGJ_iWxUvaHzCSNDMvp7K1Cu620rT5VXCBzDi5NIXuHaCQ7KOzoMT5m5Upb-kG0TjERWogVPUjP8sY4H5AY3PYGkmZfjaRFn6QDth2Fk1fl1-DQffDFsUzuzLvfnbplLr6LfHJnAJFUvsbQpYd_F8-yOcP0JmMn-_Q8P2gtLxD4kL_ofy4cPxi66h6Apc3IeN-7bqd059lmo2uBn_mAZYUdpT8Zo83PeM2ShioUlpUXCCtqnmN4N6R3w2whZfp0Qm-9-9Hy9uGbVb5eNS24rN1XZ27JveT7LRSMU213wqdiKIOOhBXTr3frz2MzXDEk7Fisx9BkzvrHBHbV0ES2mm2zZgha3GqTXw1qH7ENr_W4BClsJL0ArT_a-oifyBFIi_QNKzeNPz439hnSy6YLRKD-3O35ZizIh4u2i7kYpwm25gnxp01zj9PG4Mg0BVrP8OlSuZJyfPslXWmmtg6_NEEh1BY
                    user:
                      id: 4
                      full_name: 'Ariful Islam'
                      email: null
                      phone: '01750840217'
                      email_verified_at: null
                      last_login: null
                      created_at: '2022-01-20T09:38:29.000000Z'
                      updated_at: '2022-01-20T09:38:29.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User login successfully.'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    example:
                      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNGU2MjkzYjk3NjgxMzgyMjM4OTIxYjQzNTlkYzRkN2YxNWJjODc5MDdjMTFjY2JkM2I0YzM3ODlmNjQyMDBkOTM0YjhmODNiYzgyNzkwNmEiLCJpYXQiOjE2NDI2NzM4NTguNjU1MzE5LCJuYmYiOjE2NDI2NzM4NTguNjU1MzI0LCJleHAiOjE2NDM5Njk4NTguNjQ4NTAxLCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.O5NNZdmSoqbwK2-wWg6rrAFtWaUUe9JnybMtuoHJBReohF0ois9N9-x7CzOPuX4aKmE61LlPsM6DbIm-yidvqfGOT73mVYoREwu2mISiqTUqsbu8mnq6Nsq6Z_rj21VbOp2-DqkWh86PPI5kpf-t_-pt1QlLAwveTVpefbnmUmfc49m-_aOnXDM2H6QKhXt9zVqlkj2tgFjKgfISqLGJ_iWxUvaHzCSNDMvp7K1Cu620rT5VXCBzDi5NIXuHaCQ7KOzoMT5m5Upb-kG0TjERWogVPUjP8sY4H5AY3PYGkmZfjaRFn6QDth2Fk1fl1-DQffDFsUzuzLvfnbplLr6LfHJnAJFUvsbQpYd_F8-yOcP0JmMn-_Q8P2gtLxD4kL_ofy4cPxi66h6Apc3IeN-7bqd059lmo2uBn_mAZYUdpT8Zo83PeM2ShioUlpUXCCtqnmN4N6R3w2whZfp0Qm-9-9Hy9uGbVb5eNS24rN1XZ27JveT7LRSMU213wqdiKIOOhBXTr3frz2MzXDEk7Fisx9BkzvrHBHbV0ES2mm2zZgha3GqTXw1qH7ENr_W4BClsJL0ArT_a-oifyBFIi_QNKzeNPz439hnSy6YLRKD-3O35ZizIh4u2i7kYpwm25gnxp01zj9PG4Mg0BVrP8OlSuZJyfPslXWmmtg6_NEEh1BY
                      user:
                        id: 4
                        full_name: 'Ariful Islam'
                        email: null
                        phone: '01750840217'
                        email_verified_at: null
                        last_login: null
                        created_at: '2022-01-20T09:38:29.000000Z'
                        updated_at: '2022-01-20T09:38:29.000000Z'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Phone number.'
                  example: 017XXXXXXXX
                password:
                  type: string
                  description: 'Password of user.'
                  example: test@example.com
              required:
                - phone
                - password
      security: []
  /api/v1/vehicle/add:
    post:
      summary: 'Add New Vehicle'
      description: 'This will add new vehicle to database'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Vehicle address successfully added'
                  code: 201
                  data: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Vehicle address successfully added'
                  code:
                    type: integer
                    example: 201
                  data:
                    type: array
                    example: []
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                manufacturer:
                  type: string
                  description: 'Name of manufacturer.'
                  example: Toyota
                model:
                  type: string
                  description: 'Model number of vehicle.'
                  example: 74CUG
                vin:
                  type: string
                  description: 'Identification number of vehicle.'
                  example: '754454'
                first_registration:
                  type: date
                  description: 'Date format should be YYYY-mm-dd'
                  example: '2020-12-12'
                kilometers_stand:
                  type: integer
                  description: 'How much vehicles can drive.'
                  example: 40
              required:
                - manufacturer
                - model
                - vin
  /api/v1/vehicle/all:
    post:
      summary: 'Get All Vehicles'
      description: 'This will select and fetched all vehicles'' data from database'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{{\n\"success\": true,\n\"message\": \"Fetched vehicles\",\n\"code\": 200,\n\"data\": [\n{\n\"id\": 2,\n\"manufacturer\": \"27575\",\n\"model\": \"28588\",\n\"vin\": \"45678d\",\n\"first_registration\": \"0222-01-20\",\n\"kilometers_stand\": 654564,\n\"created_at\": \"2022-01-20T09:44:16.000000Z\",\n\"updated_at\": \"2022-01-20T10:03:33.000000Z\"\n},\n{\n\"id\": 3,\n\"manufacturer\": \"Toyota\",\n\"model\": \"285TC\",\n\"vin\": \"96876\",\n\"first_registration\": \"1997-01-20\",\n\"kilometers_stand\": 40,\n\"created_at\": \"2022-01-20T09:44:32.000000Z\",\n\"updated_at\": \"2022-01-20T09:44:32.000000Z\"\n},\n{\n\"id\": 4,\n\"manufacturer\": \"BMW\",\n\"model\": \"BM54\",\n\"vin\": \"78654F\",\n\"first_registration\": \"1997-01-20\",\n\"kilometers_stand\": 140,\n\"created_at\": \"2022-01-20T09:44:55.000000Z\",\n\"updated_at\": \"2022-01-20T09:44:55.000000Z\"\n},\n{\n\"id\": 5,\n\"manufacturer\": \"BMW\",\n\"model\": \"BM754\",\n\"vin\": \"23456B\",\n\"first_registration\": \"2022-01-20\",\n\"kilometers_stand\": 180,\n\"created_at\": \"2022-01-20T09:45:18.000000Z\",\n\"updated_at\": \"2022-01-20T09:45:18.000000Z\"\n},\n{\n\"id\": 6,\n\"manufacturer\": \"Audi\",\n\"model\": \"AUD78541\",\n\"vin\": \"854694\",\n\"first_registration\": \"2022-01-20\",\n\"kilometers_stand\": 180,\n\"created_at\": \"2022-01-20T09:45:32.000000Z\",\n\"updated_at\": \"2022-01-20T09:45:32.000000Z\"\n}\n]\n}"
      tags:
        - Endpoints
  '/api/v1/vehicle/edit/{id}':
    post:
      summary: 'Edit Vehicle'
      description: 'This will edit vehicle data'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'User address successfully updated'
                  code: 200
                  data: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User address successfully updated'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: array
                    example: []
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                manufacturer:
                  type: string
                  description: 'Name of manufacturer.'
                  example: Toyota
                model:
                  type: string
                  description: 'Model number of vehicle.'
                  example: 74CUG
                vin:
                  type: string
                  description: 'Identification number of vehicle.'
                  example: '754454'
                first_registration:
                  type: date
                  description: 'Date format should be YYYY-mm-dd.'
                  example: '2020-12-12'
                kilometers_stand:
                  type: integer
                  description: 'How much vehicles can drive.'
                  example: 40
              required:
                - manufacturer
                - model
                - vin
    parameters:
      -
        in: path
        name: id
        description: 'It will be the id of vehicle in database.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/vehicle/delete/{id}':
    post:
      summary: 'Delete Vehicle'
      description: 'This will delete data from database'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Vehicle successfully deleted'
                  code: 200
                  data: []
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Vehicle successfully deleted'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: array
                    example: []
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'It will be the id of vehicle in database.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/vehicle/view/{id}':
    post:
      summary: 'View Single Vehicle'
      description: 'This will show single vehicle'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer <token>'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"success\": true,\n\"message\": \"Vehicle fetched\",\n\"code\": 200,\n\"data\": {\n\"id\": 2,\n\"manufacturer\": \"27575\",\n\"model\": \"28588\",\n\"vin\": \"45678d\",\n\"first_registration\": \"0222-01-20\","
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'It will be the id of vehicle in database.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: ''
  -
    name: Endpoints
    description: ''
